// 7 - Project- Add Presistence to Genres API
// EXPRESS FOLDER AND ROUTES FOLDER

/*
Since the entry file is index.js we can just use: nodemon

PSOTMAN
POST http://localhost:3000/api/genres   
{ 
    "name": "Thriller"
}
result: id generated by mongo


GET   http://localhost:3000/api/genres

Updating
copy the id
PUT   http://localhost:3000/api/genres/65bf446e1e604d05ed75087f
{ 
    "name": "1234"
}

test update with 
"name": ""
with wrong id


DELETE http://localhost:3000/api/genres/65bf446e1e604d05ed75087f
*/

// INDEX.JS
const mongoose = require("mongoose");
const genres = require("./routes/genres");
const express = require("express");
const app = express();

mongoose
  .connect("mongodb://localhost/vidly")
  .then(() => console.log("Connected to MongoDB..."))
  .catch((err) => console.log("Could not connect to MongoDB..."));

app.use(express.json());
app.use("/api/genres", genres);

const port = process.env.PORT || 3000;
app.listen(port, () => console.log(`Listening on port ${port}...`));
